baseURL: https://elleli.netlify.app/
languageCode: en-us
title: Portfolio Website for Elle
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Elle
  blog: {}
  contact:
    address:
      - city: Hangzhou, Zhejiang 310000
        country: China
        street: 70 Wenyi Rd
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: eli.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (086) 137-5719-5824
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      #- icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/ElleMengtianLi
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/elle-li-2000
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: My first step towards R
        title: Pre programme assignment
        url: projects/pre_programme_assignment
      - image: pic02.jpg
        subtitle: Look at how cool it is!
        title: A beautiful plot
        url: projects/plot
      - image: pic03.jpg
        subtitle: A group work...
        title: Homework 1
        url: projects/homework1
      - image: pic04.jpg
        subtitle: Another group work...
        title: Homework 2
        url: projects/homework2
      - image: pic05.jpg
        subtitle: More group work...
        title: Homework 3
        url: projects/homework3
      #- image: pic06.jpg
        #subtitle: The last group work...
        #title: Group Project
        #url: projects/
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Interesting projects I had worked on"
    title: My blogs
    url: blogs
  
  
  